[package]
name = "pocky"
version = "0.1.0"
authors = ["McKayla Washburn <mckayla@hey.com>"]
description = ""
keywords = []
license = "MIT"
homepage = "https://github.com/aslilac/pocky"
repository = "https://github.com/aslilac/pocky"
documentation = "https://docs.rs/pocky"
edition = "2021"

[dependencies]
chrono = "0.4.22"
markdown = "0.3.0"
